### ISSUE TITLE
3060ti跑不了吗？

### ISSUE THREAD

**Issue by sauces88** [psyai-net/CVCUDA_FaceStoreHelper-release#5]
2023-07-19 19:12:11,295 - /home/s1inys/project/CVCUDA_FaceStoreHelper/config.py[line:13] - INFO: device: cuda
Traceback (most recent call last):
  File "/home/s1inys/project/CVCUDA_FaceStoreHelper/serial_pipeline.py", line 80, in <module>
    cropped_face_all, cvcuda_inverse_affine_matrices = run_inpainting_1(input_img_list, affine_matrices,
  File "/home/s1inys/project/CVCUDA_FaceStoreHelper/api.py", line 91, in run_inpainting_1
    input_nvcv_image = cvcuda_utils.to_nvcv_image(imglist[index])
  File "/home/s1inys/project/CVCUDA_FaceStoreHelper/cvcuda_utils/cvcuda_util.py", line 161, in to_nvcv_image
    return nvcv.as_image(to_cuda_buffer(host_data))
  File "/home/s1inys/project/CVCUDA_FaceStoreHelper/cvcuda_utils/cvcuda_util.py", line 100, in to_cuda_buffer
    dev = torch.as_tensor(host_data, device="cuda").cuda()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.78 GiB total capacity; 6.65 GiB already allocated; 77.69 MiB free; 7.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by cucdengjunli** [comment]
我们调整一下batchsize，做个可选项，现在代码封装得有点死板

**Comment by sauces88** [comment]
ok，感谢
